import './Theme.css.proxy.js';
/* src/globals/Theme.svelte generated by Svelte v3.29.4 */
import { SvelteComponent, init, safe_not_equal } from "../../web_modules/svelte/internal.js";

class Theme extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Theme;