import './Button.css.proxy.js';
/* src/components/Button.svelte generated by Svelte v3.29.4 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let input;

	return {
		c() {
			input = element("input");
			attr(input, "class", "ts_button svelte-zaz320");
			input.value = "Hello";
			attr(input, "type", "button");
		},
		m(target, anchor) {
			insert(target, input, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(input);
		}
	};
}

class Button extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Button;